# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Semantic-search-engine
email: sreeharipv1994@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  "Creating a semantic search engine by making use of genism-topic modelling and flask framework
  This is a simple web application built using flask framework in Python that performs semantic searching of a pre-prepared MongoDB database containing information about tourist destinations in Kerala(one of the states in India). So for a given user query such as "I wish to have some adventures in Kerala, this web application will display top search results relating to Adventure Tourism in Kerala in a Google like manner with title,url for redirection to respective webpages and short description for each result. Even for beginners,this entire application can be built from scratch in a matter of four or five hours. Although this project in its current form is a web app that caters to "Kerala Tourism", making a tiny change(specifically in the Python List containing website URL's used for scrapping) can make this search engine work for any other text-data related task that you have in mind. For instructions on how to clone this repo and see the application in action, scroll down to bottm.
  (Not yet complete, will be updated later)""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: cayman
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
